import Head from 'next/head'
import Buttons from './component/button'

export default function Home() {
  return (
    <>
      <Head>
        <title>Components | Publishing Guide</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Buttons />
    </>
  )
}
